### ISSUE TITLE
Export Import button is not visible if landscape

### ISSUE THREAD

**Issue by jsikio** [PawelSpoon/harbour-olive-goes-shopping#17]
If phone is landscape (or with Gemini PDA) Import Export button is not visible.
![nayttokuva_20190303_001](https://user-images.githubusercontent.com/5907426/53688141-ea09e480-3d47-11e9-81c2-be62719af9db.png)

**Comment by PawelSpoon** [comment]
space before recipes should be f(totalHight), use also * Theme.pixelRatio to fit i.e. Aquafish

**Comment by PawelSpoon** [comment]
released in openrepos.net / version 2.2

**Comment by PawelSpoon** [comment]
i will update jolla store, when fi_FI translation was confirmed to be working in openrepos.net version.
you can try out the fix using storeman

**Comment by jsikio** [comment]
Agree that fix work. Tested with Gemini PDA and Xperia X.
