### ISSUE TITLE
Adding the french translation to the application

### ISSUE THREAD

**Issue by lturpinat** [PawelSpoon/harbour-olive-goes-shopping#33]
I made a french translation on transifex. I tried it on the emulator (and it looks fine for now), I guess it could be added to the application?

Cheers,

**Comment by PawelSpoon** [comment]
Yes, usually i get a mail from transifex, when a translation is done.
If you think the current state is fine, i can include it. Do you make a pull request or should i include it ?
Thanks !
P

On Tuesday, January 14, 2020, Louis Turpinat wrote:
> I made a french translation on transifex. I tried it on the emulator (and it looks fine for now), I guess it could be added to the application?
> 
> Cheers,
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PawelSpoon/harbour-olive-goes-shopping/issues/3

-- 
Gesendet von meinem Sailfish Gerät

**Comment by lturpinat** [comment]
> Yes, usually i get a mail from transifex, when a translation is done. If you think the current state is fine, i can include it. Do you make a pull request or should i include it ? Thanks ! P
> […](#)
> On Tuesday, January 14, 2020, Louis Turpinat wrote: I made a french translation on transifex. I tried it on the emulator (and it looks fine for now), I guess it could be added to the application? Cheers, -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #3
> -- Gesendet von meinem Sailfish Gerät

I made a pull request ;)
Cheers,
L

**Comment by PawelSpoon** [comment]
I will try to build a new version weekend !
Thanks !
P

On Wednesday, January 15, 2020, Louis Turpinat wrote:
> > Yes, usually i get a mail from transifex, when a translation is done. If you think the current state is fine, i can include it. Do you make a pull request or should i include it ? Thanks ! P
> > […](#)
> > On Tuesday, January 14, 2020, Louis Turpinat wrote: I made a french translation on transifex. I tried it on the emulator (and it looks fine for now), I guess it could be added to the application? Cheers, -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #3
> > -- Gesendet von meinem Sailfish Gerät
> 
> I made a pull request ;)
> Cheers,
> L
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/PawelSpoon/harbour-olive-goes-shopping/issues/33#issuecomment-57476190

-- 
Gesendet von meinem Sailfish Gerät

**Comment by PawelSpoon** [comment]
i thing there is a About.qml~ too much in the commit. I will delete it again ok ?

**Comment by PawelSpoon** [comment]
if you want to change the name of the app also in french, you will need to adapt the .deskop file

**Comment by PawelSpoon** [comment]
i have commited now all my local changes, source should reflect 3.2. shall i send you the 3.2 rpm ?

**Comment by lturpinat** [comment]
> i thing there is a About.qml~ too much in the commit. I will delete it again ok ?

My bad, sorry!

> i have commited now all my local changes, source should reflect 3.2. shall i send you the 3.2 rpm ?

I already checked the translation by compiling myself. Though I didn't do that with the whole thing. I'll gladly give it a look if you send me the rpm ;)

**Comment by PawelSpoon** [comment]
included in 3.2
