### ISSUE TITLE
Add Option to edit present Items

### ISSUE THREAD

**Issue by EarthlingX** [PawelSpoon/harbour-olive-goes-shopping#5]
Once an item is created, yet it is not possible anymore to edit this item. Would it be possible to add a feature for editing already created items?

Thanks a lot! :-)

**Comment by PawelSpoon** [comment]
yes i know. the main problem: i am using lonpressbfor deletion
i.dont.want.a context menu here

idea how.to.solve that ?

**Comment by PawelSpoon** [comment]
press could still check/ uncheck
longpress opens context menu.with.wdit / delete

an pull up : delete all checked.might be usefull

i would allow.to.modify all items, even those.that came from a recipe

however i am now on a long term vaccation and want to use that for travelling and learning drums, so it will take months ...

**Comment by PawelSpoon** [comment]
i had a look on code (after a looong time) and app-
this request makes only sense for 'Anything'. there is no need to change an item that comes from a db.
do you agree ?

**Comment by EarthlingX** [comment]
Thanks for your comment! :-)

> there is no need to change an item that comes from a db.?

I am sorry, I don't understand what you mean: In my idea I thought, editing an item for example if you have a mispelling in the name or the item name has changed or something similar. :-) Probably this does also affect the DB I guess?

But if this is too difficult to implement: No worries! :-) It could be also a solution to just export the database, edit the desired item name in the textfile and re-import it to the app. :-)

**Comment by EarthlingX** [comment]
Actually I figured out that it is possible to edit items: Just open the item in the "Manage" menue and you can change name, category etc. Is this new? :-)

**Comment by PawelSpoon** [comment]
implemented in 1.5.
get latest from openrepos

**Comment by PawelSpoon** [comment]
@EarthlingX : maybe we got a misunderstanding here:
it was always possible to modify / edit items in the database (db), in the item list, where you acutally pick them from.

It was not possible to modify an item in the shopping list, once it was added.
so this is what i did now: you can even modify the items in the shopping list with a longpress.
