### ISSUE TITLE
Export / Import does not work with SD card since 2.2

### ISSUE THREAD

**Issue by PawelSpoon** [PawelSpoon/harbour-olive-goes-shopping#8]
mount point was changed, need to adapt that

**Comment by jsikio** [comment]
Try to change ExportPage.qml line 77 var internalStorage = "/media/sdcard/" to
        var internalStorage = "/run/media/nemo/"

**Comment by PawelSpoon** [comment]
Thank you !
tried, but no improvement

**Comment by jsikio** [comment]
Strange, because I tested and it works with my Gemini PDA device. Didn't work with emulator.

**Comment by PawelSpoon** [comment]
it did not work on experia x. that s where i did test it.

i once wanted to take over the code from ownkeepass. the developer there did fix the issue.
but i did not find the time to merge it correctly and it was not my most important topic.

**Comment by PawelSpoon** [comment]
btw. i did update the source now

**Comment by jsikio** [comment]
Thanks! 
This patch works for me, both XPeriaX and Gemini PDA.
[ExportPage_diff.txt](https://github.com/PawelSpoon/harbour-olive-goes-shopping/files/2948310/ExportPage_diff.txt)
![Näyttökuva_20190309_001](https://user-images.githubusercontent.com/5907426/54070731-629f0280-426c-11e9-834e-9654f834f493.png)

**Comment by PawelSpoon** [comment]
cool thanks !!

will try to merge it asap

**Comment by PawelSpoon** [comment]
released in openrepos
